### PR TITLE
Add more dock support

### PR DESCRIPTION
**Pull request by Lash-L**
#160 #130 

- Removed some depreciated stuff in sensor
- Removed handle_coord update and just did it all native value
- Add sensor for dock error
- add a bunch of services/ sensors for other dock functionality.

Needs new version of pypi class before it can merged.

And I would like to get it tested, but I will be able to do that when the pypi package is pushed.

### CODE REVIEW

**Comment by humbertogontijo** [comment]
Version 0.1.11.dev released with changes on python-roborock

**Comment by Lash-L** [comment]
@humbertogontijo using this as it's a means to communicate and keep track of things. 

So we have added a lunch since the most recent release. Perhaps we make some goals for a 2.0 release? Then we release it as a pre-release have the users in the corresponding issues help test the pre release, then if it works well do a full release?

Id like to get a few things done before the next release:

 - get this PR finished
 - add room mapping support (offline only) and make it so services can directly reference room names
 - add dhcp discovery so that users don't have to enter in the ip but this is only if I can figure out how to get the mac address in non dhcp discovery this is a low priority

I'm not sure how much of offline you have added to this repo, but I'd be happy to do any of that as well.

What are your thoughts? I'm just here to help, don't want to overstep - this is your repo

**Comment by humbertogontijo** [comment]
DHCP discovery is not possible since we need to relate ip to local_key. At least I couldn't find a way to do it.
Only command get_map_v1 is not working now. I'm starting to think that the map data do not come from the tcp connection, but I can't tell how to get it

**Comment by Lash-L** [comment]
Sorry I should have been more clear. 

You would still do the normal setup after dhcp discovery, you would just go into it with the ip address for the vacuum already determined.

Then when you login you get local key.

As far as get map - I'd be curious if any of the protocol 5s afterwards contain the information. I haven't checked (I can tomorrow) but are there any protocol 5 after the get map command? 

We're you able to get multi map to work?

**Comment by humbertogontijo** [comment]
Yes, get multi map worked. I still need to upload it

**Comment by Lash-L** [comment]
@humbertogontijo 

Here's a question from the core PR that hopefully you can give me some insight for:

"To clarify: I was asking a different question: is this actually polling or subscribing? The client library is called mqtt but it appears to be polling.... If it really is subscribing, then its not clear you need to poll for latest device state so often. I wasn't saying to change the manifest, but hoping for clarification on what is actually happening.

I also reviewed the library and it does not seem to implement async correctly. For example, in the shutdown method it just calls the sync methods form inside async. I have some serious concerns about this client library being well behaving asyncio. Does my concern make sense or am I missing something?"

What are your thoughts?

**Comment by humbertogontijo** [comment]
It uses mqtt, but it is still polling. The device do not reports status regularly, it listen to a topic and replies to another.
What are your concerns about the async behavior?

**Comment by Lash-L** [comment]
> It uses mqtt, but it is still polling. The device do not reports status regularly, it listen to a topic and replies to another. What are your concerns about the async behavior?

Here is his specific message:

https://github.com/home-assistant/core/pull/89456/files#r1157574879

Want to attempt to answer his question? I'm not nearly as knowledgeable about the foundation for the client as you are.

Otherwise, I can respond back and try to handle it if you would like me to.

**Comment by humbertogontijo** [comment]
I answered that

**Comment by Lash-L** [comment]
> I answered that

Appreciate it

**Comment by Lash-L** [comment]
He responded back whenever you get a chance @humbertogontijo

**Pull request closed without merging**
