### PR TITLE
feat:  Validate with HACS

### PR DESCRIPTION
**Pull request by cdnninja**
If these tests past a simple PR can have this added to the HACS store so users don't need to add a custom repo.  If interested I can drop a PR to complete this.

### CODE REVIEW

**Comment by Lash-L** [comment]
Haha what are the odds - I had just added this to my PR #214

**Comment by cdnninja** [comment]
Literally minutes apart!   

Lookings like two things need to happen the checks pass. 

1.  Topics being added to the repo.  @humbertogontijo  will need to do this.
2. The brand needs to be added here: https://github.com/home-assistant/brands

**Comment by Lash-L** [comment]
Interesting - I would think that it could grab it from core_integrations in addition to custom_integrations. I guess I'll need to make a PR to copy from core_integration/roborock to custom_integrations/roborock

**Comment by Lash-L** [comment]
Ah - on second thought looks like it wont get approved

'Custom integrations that override core integrations will not be accepted, you can still use it as a [custom repository](https://hacs.xyz/docs/faq/custom_repositories)'

Technically there is currently a core integration called roborock., as it is a virtual integration of the Xiaomi one.

And when my PR for making this a core integration goes through - that will also be problematic for their requirements.

**Comment by cdnninja** [comment]
I am giving it a try here: https://github.com/home-assistant/brands/pull/4240

**Comment by Lash-L** [comment]
> I am giving it a try here: https://github.com/home-assistant/brands/pull/4240

The comment I copied was from the hacs docs. You are more than welcome to try, I'm unsure if hacs will accept. Keep us updated though

**Comment by cdnninja** [comment]
Interesting.  So not the brands issue but rather HACS itself.

**Comment by Lash-L** [comment]
> Interesting.  So not the brands issue but rather HACS itself. 

Looking at the info on your PR checks - it looks like it is an issue on both ends

**Comment by humbertogontijo** [comment]
Topics added to the repository

**Review by humbertogontijo — APPROVED** [review]

**Comment by Lash-L** [comment]
@humbertogontijo i wouldn't merge this one in

**Comment by humbertogontijo** [comment]
Yeah, I will not. I'll wait on that PR

**Comment by Lash-L** [comment]
Closing this for now as it seems not doable with HACS/ HASS requirements. If that changes we can try again

**Pull request closed without merging**
