### PR TITLE
bump python-Roborock to 0.32.3

### PR DESCRIPTION
**Pull request by Lash-L**

### CODE REVIEW

**Comment by Lash-L** [comment]
If you were trying to include other changes in this release ignore this. Just thought I’d try to make your life a bit easier

**Comment by humbertogontijo** [comment]
Thank you

**Review by humbertogontijo — APPROVED** [review]

**Comment by Lash-L** [comment]
Maybe this should wait for https://github.com/humbertogontijo/python-roborock/pull/103

**Comment by humbertogontijo** [comment]
Yes. Let's wait on that

**Review by humbertogontijo — APPROVED** [review]
Thanks again

**Pull request merged**
