### PR TITLE
adding translation keys for sensors and binary sensors

### PR DESCRIPTION
**Pull request by Lash-L**
HA 2023.4 added a new functionality - translation keys. Which allow you to translate the name of an entity. I'm not sure what will happen if someone uses it in 2023.3

I added it in english in all of the translation files for now.

### CODE REVIEW

**Comment by Lash-L** [comment]
Need to retest after merge conflict changes.

**Comment by Lash-L** [comment]
This should be good to go now @humbertogontijo 

Also fixed issue with the config flow. Needed to turn the user_data into a dict.

**Comment by humbertogontijo** [comment]
Did you find out what happens using this branch with HA 2023.3 or earlier?

**Comment by Lash-L** [comment]
I don't have anyway to test as I am on 2023.4, but I do believe the integration would fail setting up the sensor and binary sensor platform as when it attempted to do so, it would have an unrecognized value of translation_key

**Pull request merged**
