### PR TITLE
feat: add `inlang` to make the contribution of translations easier

### PR DESCRIPTION
**Pull request by felixhaeberle**
Let me know what changes you request for merging this PR.

### Description
This pull request adds the possibility for contributors and translators to manage translations in a UI instead of files with no overhead for the maintainers.

To get a UI for translations contained in this repository, an [inlang.config.js](https://inlang.com/documentation/config) has been created at the root of the repository. Furthermore, I added the few missing translations. If you want, I can add a small i18n section to the documentation on the [README](https://github.com/humbertogontijo/homeassistant-roborock).

### Overview
The changes of this PR and a live instance of the editor can be previewed with the following link https://inlang.com/editor/github.com/felixhaeberle/homeassistant-roborock.
Note: This link should be changed to point to `humbertogontijo` instead of `felixhaeberle` after this PR has been merged.

### Limitations
Certain actions are slow
Inlang is running entirely on git, giving tremendous CI/CD and contribution power to localization. That means that the whole `homeassistant-roborock` repo is cloned into the browser which makes certain actions like the initial load and pushing changes slow. Those limitations will be fixed with future releases and require no input from `homeassistant-roborock`.

232016041-ec0c3da3-94a9-4492-85dd-d8478c66d945 (1)

### Preview
Preview the messages on https://inlang.com/editor/github.com/felixhaeberle/homeassistant-roborock.

### CODE REVIEW

**Comment by Lash-L** [comment]
Looks interesting - I don't have much time to dive into it right now - but if I were to add a new translation key, what would I need to do?

Is there a step for that in the ui? Or do I need to do it like I currently do it by adding it to en.json and then copying it to each translation file?

**Comment by felixhaeberle** [comment]
We provide you with an VS Code extension to automatically extract strings for an id and add it to your reference language ("en"). The VS Code extension is currrently under development and will be released early May. 

Until then, it's a manual process, so you would add them in your reference language and after that, you can use the UI. If you made a mistake, inlang lints all the translations for missing keys or references in all languages when visiting the UI and will provide you with warnings and point you to the missing translations. 👍

**Comment by humbertogontijo** [comment]
Yes. This looks interesting. 
HA do not expect the options to have sub objects.
If inlang supports keeping the dots in the json key, lets keep the dots. 
Otherwise another PR to change the keys from using dots to another character might be needed

**Comment by felixhaeberle** [comment]
@humbertogontijo Am I allowed to change the code to use underscores?:)

**Comment by humbertogontijo** [comment]
On second thought, maybe something other than underscore? Underscore is commonly used in keys

**Comment by felixhaeberle** [comment]
Alright! I go for `:`. Thank you!! 🙏

**Comment by felixhaeberle** [comment]
@Lash-L @humbertogontijo Hey there, just a small check-in. Do you want me to do further actions?

**Review by humbertogontijo — APPROVED** [review]

**Comment by humbertogontijo** [comment]
> @Lash-L @humbertogontijo Hey there, just a small check-in. Do you want me to do further actions?

Nope.
Merged

**Pull request merged**
