### PR TITLE
add functionality to reset consumables w button

### PR DESCRIPTION
**Pull request by Lash-L**
This is working online only right now. The prefix for reset consumables is wrong, and I am without my mac right now so I can't connect my phone to reverse engineer the prefix. If you are able to - then this should be good to go

### CODE REVIEW

**Review by humbertogontijo — CHANGES_REQUESTED** [review]

**Comment by humbertogontijo** [comment]
Fixed prefix in main branch

**Comment by Lash-L** [comment]
@humbertogontijo 

Offline support in the custom integration seems completely broken.

I was getting errors about wrong padding and all sorts of stuff - it ended up having a bunch of errors. I left it running for a few minutes before I realized. 

Now I'm completely unable to even connect offline using core(which was working before I tried custom).

There's a chance it could be an issue with my VPN as I'm not currently home, but it could also be some kind of time out, once I'm  back home I'm gonna try restarting my vacuum and see if it lets me connect.

As a secondary issue, 

```await self.loop.sock_connect(self.socket, (self.ip, 58867))``` in local_api Can somehow not timeout? I tried implementing socket.settimeout but that doesn't work for sock_connect. 

The async_timeout somehow doesn't catch the super long timing. But since my robot isn't working right now, I guess it still connects and then freezes? the return await fut inside sock_connect is what it gets stuck on.

Any ideas how I could get the timeout to successfully work there? I don't see this being an issue for anyone else, but it completely freezes my home assistant instance because of this failed connection. 

I tried testing with my wifi off so I couldn't reach it, and that fails with no problems.

**Comment by humbertogontijo** [comment]
Are you using latests version? self.loop.sock_connect is gone since 6.16

**Comment by Lash-L** [comment]
Ah - I haven't bumped the core version - so I am not. I will bump the core version and go from there. But I believe there are still other offline issues - as I was using latest version on custom

**Comment by humbertogontijo** [comment]
Yes. I haven't figured it out yet. But looks like when I try a command that fails on develop container, my roborock integration from home instance also disconnects.

**Comment by Lash-L** [comment]
Interesting - are you able to connect again by restarting your vacuum? What gets you back in?

I bumped the version on my core dev container, but I'm still unable to connect, so I am assuming I need to restart the vacuum

**Comment by humbertogontijo** [comment]
Can you send me the issue you are having?
No need to restart the vacuum.
Try disabling the integration on others HA instances

**Comment by Lash-L** [comment]
I had all my erorrs written down and then I stepped away for a bit. And it started working.

I think I was definitely timed out in some way. Or perhaps there was a lingering connection that wasn't disconnecting.

**Comment by humbertogontijo** [comment]
A new version is building hopefully fixing this

**Comment by Lash-L** [comment]
Sounds good - as an aside, we should probably async disconnect the map_api in addition to the api in cooridnator release(). 

I was gonna make a PR to do it, but if you are already making changes, it probably makes sense for you to just change that as well

**Comment by humbertogontijo** [comment]
Oh, thats true. I'll add it

**Comment by Lash-L** [comment]
Do you have any issue with me re-adding the update() function to DeviceProps?

**Comment by humbertogontijo** [comment]
No, we can get update function back

**Pull request merged**
